title: Pages Demo
description: >-
  Create project docs with minimal friction.
baseurl: "pages-demo"
url: "https://zacharlie.github.io/pages-demo"
github_username:  zacharlie
theme: jekyll-theme-cayman
show_downloads: false
exclude:
  - "README.md"