title: Pages Demo
description: >-
  The pages demo shows the contents, workflow, actions, and outputs from
  some common static site frameworks so developers can pick a process for
  producing and maintaining project docs with minimal friction.
baseurl: ""
url: "https://zacharlie.github.io/pages-demo"
github_username:  zacharlie
theme: jekyll-theme-cayman
show_downloads: false
header-bg-color: "#ecb44b"
header-bg-color-secondary: "#57a0c7"
